# Generated by Django 3.0.3 on 2020-02-04 09:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Стаття', 'verbose_name_plural': 'Статті'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Коментарій', 'verbose_name_plural': 'Коментарі'},
        ),
        migrations.AddField(
            model_name='article',
            name='article_rate',
            field=models.FloatField(default=0.0, verbose_name='Рейтинг статті'),
        ),
    ]
