# Generated by Django 3.0.3 on 2020-03-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='kvartal',
            new_name='Kvartal',
        ),
        migrations.RenameField(
            model_name='indicator',
            old_name='year',
            new_name='Year',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='C',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='E',
        ),
        migrations.RemoveField(
            model_name='indicator',
            name='V',
        ),
        migrations.AddField(
            model_name='indicator',
            name='Income',
            field=models.DecimalField(decimal_places=0, default=100, max_digits=5, verbose_name='Чистий дохід'),
            preserve_default=False,
        ),
    ]
