# Generated by Django 3.0.3 on 2020-03-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200309_1340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='indicator',
            options={'verbose_name': 'Показник ефективності', 'verbose_name_plural': 'Показники ефективності'},
        ),
        migrations.AddField(
            model_name='indicator',
            name='C',
            field=models.DecimalField(decimal_places=0, default=1235, max_digits=5, verbose_name='Сумарні змінні витрати'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='E',
            field=models.DecimalField(decimal_places=0, default=1235, max_digits=5, verbose_name='Сумарні постійні витрати'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='V',
            field=models.DecimalField(decimal_places=0, default=1235, max_digits=5, verbose_name='Обєм продаж'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='kvartal',
            field=models.DecimalField(decimal_places=0, default=1235, max_digits=1, verbose_name='Квартал'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indicator',
            name='year',
            field=models.CharField(default=2020, max_length=4, verbose_name='Рік'),
            preserve_default=False,
        ),
    ]
